[project]
name = "das"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dask>=2025.11.0",
    "h5netcdf>=1.7.3",
    "xarray>=2025.11.0",
]
[tool.setuptools.package-data]
das = ["/cables/resources/*.json"]
